[package]
name = "fpcalc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
base64 = "0.22.1"
chrono = "0.4.38"
clap = { version = "4.5.19", features = ["derive"] }
rusty-chromaprint = {path = "../chromaprint"}
symphonia = { version = "0.5.2", features = ["all"]}
